apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: chatbot-secrets
  namespace: chatbot

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: chatbot-secrets

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: queriesresolve-prod
        property: DATABASE_URL

    - secretKey: REDIS_URL
      remoteRef:
        key: queriesresolve-prod
        property: REDIS_URL

    - secretKey: JWT_ACCESS_SECRET
      remoteRef:
        key: queriesresolve-prod
        property: JWT_ACCESS_SECRET

    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        key: queriesresolve-prod
        property: JWT_REFRESH_SECRET

    - secretKey: OPENAI_PRO_API_KEY
      remoteRef:
        key: queriesresolve-prod
        property: OPENAI_PRO_API_KEY