# ServiceAccount used for IRSA.
apiVersion: v1
kind: ServiceAccount

metadata:
  name: chatbot-backend
  namespace: chatbot

  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::590183864134:user/eks-deployer