ALTER TYPE "BillingCycle" ADD VALUE IF NOT EXISTS 'TRIAL';
ALTER TYPE "BillingCycle" ADD VALUE IF NOT EXISTS 'QUARTERLY';
ALTER TYPE "BillingCycle" ADD VALUE IF NOT EXISTS 'HALF_YEARLY';
ALTER TYPE "BillingCycle" ADD VALUE IF NOT EXISTS 'YEARLY';
